//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyThirdProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_student  //fully encapsulated class
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "First Name is required")]
        public string FName { get; set; }

        [Required(ErrorMessage = "Last Name is required")]
        public string LName { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage ="Please enter email address in proper format")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Mobile number is required")]
        [MaxLength(13,ErrorMessage = "Please enter mobile number like +xxxxxxxxxxxx")]
        [MinLength(13,ErrorMessage = "Please enter mobile number like +xxxxxxxxxxxx")]
        [RegularExpression(@"^\+[0-9]{12}$", ErrorMessage ="Mobile number format +011234567890")]
        public string Mobile_Number { get; set; }
        public string About { get; set; }
    }
}
